general:
  auth:
    default: dev
project:
  name: quickstart-solodev-eks
  owner: help@solodev.com
  regions:
  - eu-north-1
  - me-south-1
  - us-east-1
  template: templates/solodev-eks-master-existing-vpc.template.yaml
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: "quickstart-solodev-eks/"
    ProvisionBastionHost: Disabled
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  build_submodules: true
tests:
  defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
  # aws:
  #   parameters:
  #     AvailabilityZones: $[taskcat_genaz_3]
  #   template: templates/amazon-eks-master-existing-vpc.template.yaml
  #   regions:
  #       - us-east-1
  # cms:
  #   parameters:      
  #     WebStackArn: $[WebStackArn]
  #     HelmLambdaArn: $[HelmLambdaArn]
  #     ClusterName: $[ClusterName]
  #     AdminPassword: $[AdminPassword]
  #     DatabasePassword: $[DatabasePassword]
  #   template: templates/solodev-eks-cms.template.yaml
  #   regions:
  #       - us-east-1
  # token:
  #   parameters:
  #     WebStackArn: $[WebStackArn]
  #     ClusterName: $[ClusterName]
  #   template: templates/solodev-eks-token.template.yaml
  #   regions:
  #       - us-east-1
