AWSTemplateFormatVersion: "2010-09-09"

Description: "Deploys the Solodev CMS helm chart into an existing kubernetes cluster (qs-1qde66ffn)"

Metadata: 

  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Cluster Settings"
        Parameters: 
          - ClusterName
          - WebStackArn
      - 
        Label: 
          default: "Optional: DNS"
        Parameters: 
          - DomainName
          - ClusterZone
      - 
        Label: 
          default: "CMS Settings"
        Parameters: 
          - AdminUser
          - AdminEmail
          - AdminPassword
          - WebsiteUrl
          - WebsiteThemeUrl
          - WebsiteThemeValues 
          - AppVersion
      - 
        Label: 
          default: "Advanced Settings"
        Parameters: 
          - DatabaseName
          - DatabasePassword
          - Namespace
          - AppSecret
          - ServiceRoleName
      - 
        Label: 
          default: "Helm Chart"
        Parameters: 
          - RepoUrl
          - DefaultCMS

Parameters:

  AdminUser:
      Description: The solodev admin username
      Type: String
      Default: 'solodev'
      AllowedPattern: .+
      ConstraintDescription: Please set admin username

  AdminPassword: 
      NoEcho: true
      Description: The solodev admin password
      Type: String
      MinLength: 1
      MaxLength: 41
      AllowedPattern: .+
      ConstraintDescription: Please set admin password

  AdminEmail:
    Type: String

  WebsiteUrl:
    Type: String
    Default: ""

  WebsiteThemeUrl:
    Type: String
    Default: ""
    Description: "Initial Website Theme URL"

  WebsiteThemeValues:
    Type: String
    Default: ""
    Description: "Initial Website Theme Values"

  DatabaseName:
      Description: The solodev database name
      Type: String
      MinLength: 1
      MaxLength: 64
      AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
      ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
      Default: 'solodev'

  DatabasePassword:
      NoEcho: true
      Description: The database root password
      Type: String
      MinLength: 1
      MaxLength: 41
      AllowedPattern: .+
      ConstraintDescription: Please set database root password

  AppSecret:
    Type: String
    Description: Secret Key for App Encryption
    Default: 'c5d3adbb98f43thc0d12f0cc8fbcd7f8'

  WebStackArn:
    Type: String

  ClusterName:
    Type: String

  ServiceRoleName:
    Type: String
    Default: "aws-serviceaccount"

  Namespace:
    Type: String
    Default: "solodev"

  RepoUrl:
    Type: String
    Default: "https://raw.githubusercontent.com/techcto/charts/master/"

  DomainName:
    Description: This is the DNS Zone for all clusters
    Type: String
    Default: ""

  ClusterZone:
    Description: This is the DNS Zone that for a single cluster
    Type: String
    Default: ""

  ClientId:
    Type: String
    Default: ""
    
  ClientSecret:
    Type: String
    Default: ""

  DefaultCMS:
    Type: String
    AllowedValues: [ "charts/solodev-cms", "charts/wordpress" ]
    Default: "charts/wordpress"
    Description: "Choose preferred CMS"

  AppVersion:
    Type: String
    Default: ""
    Description: "CMS version"

Conditions:
  IsDefault: !Equals [!Ref DomainName, '']
  NotDefault:
      "Fn::Not":
        - Condition: IsDefault
  cleanInstall: !Equals [!Ref WebsiteUrl, '']
  AddWebsite:
      "Fn::Not":
        - Condition: cleanInstall
  installTheme: !Equals [!Ref WebsiteThemeUrl, '']
  InstallSolodev: !Equals [!Ref DefaultCMS, 'charts/solodev-cms']
  InstallWordpress: !Equals [!Ref DefaultCMS, 'charts/wordpress']

Resources:

  Marketplace:
    Type: "Custom::WebStack"
    Version: '1.0'
    Properties:
      ServiceToken: !Ref WebStackArn
      ClusterName: !Ref ClusterName
      Namespace: !Ref Namespace
      ServiceRoleName: !Ref ServiceRoleName
      Marketplace:
        Enable: "true"

  Wordpress:
    Condition: InstallWordpress
    DependsOn: Marketplace
    Type: "AWSQS::Kubernetes::Helm"
    Properties:
      ClusterID: !Ref ClusterName
      Chart: !Join [ '.', [!Ref RepoUrl, !Ref DefaultCMS, 'tgz' ]]
      Name: !Ref AWS::StackName
      Namespace: !Ref Namespace
      Version: !Ref AppVersion
      ValueYaml: !Sub |
        serviceAccountName: "${ServiceRoleName}"
        wordpress:
          settings:
            appSecret: ${AppSecret}
            appUser: ${AdminUser}
            appPassword: ${AdminPassword}
            appEmail: ${AdminEmail}
            websiteUrl: "${AWS::StackName}.${ClusterZone}"
            websiteTheme: ${WebsiteThemeUrl}
            websiteThemeValues: "${WebsiteThemeValues}"
            dbName: ${DatabaseName}
            dbPassword: ${DatabasePassword}
          domainName: "${DomainName}"
          clusterZone: "${ClusterZone}"

  SolodevCMS:
    Condition: InstallSolodev
    DependsOn: Marketplace
    Type: "AWSQS::Kubernetes::Helm"
    Properties:
      ClusterID: !Ref ClusterName
      Chart: !Join [ '.', [!Ref RepoUrl, !Ref DefaultCMS, 'tgz' ]]
      Name: !Ref AWS::StackName
      Namespace: !Ref Namespace
      Version: !Ref AppVersion
      ValueYaml: !Sub |
        serviceAccountName: "${ServiceRoleName}"
        solodev:
          image:
            registry: "docker.io"
            repository: "solodev/cms"
            tag: latest
            pullPolicy: IfNotPresent
          settings:
            appSecret: ${AppSecret}
            appUser: ${AdminUser}
            appPassword: ${AdminPassword}
            appEmail: ${AdminEmail}
            websiteUrl: ${WebsiteUrl}
            websiteTheme: ${WebsiteThemeUrl}
            websiteThemeValues: "${WebsiteThemeValues}"
            dbName: ${DatabaseName}
            dbPassword: ${DatabasePassword}
            clientId: ${ClientId}
            clientSecret: ${ClientSecret}
          pullSecret: solodev
          domainName: ${DomainName}
          clusterZone: ${ClusterZone}
        ui:
          image:
            registry: "docker.io"
            repository: "solodev/cms-apache"
            tag: latest

Outputs:
    
    AdminUsername: 
        Description: Solodev admin username.
        Value: !Ref AdminUser
    
    AdminPassword: 
        Description: Solodev admin password.
        Value: !Ref AdminPassword

    AdminUrl: 
        Description: Point your DNS to this CNAME.
        Value: !Join ["", [ !Ref "AWS::StackName", ".", !Ref ClusterZone ]]

    WebsiteUrl: 
        Condition: AddWebsite
        Description: The public website address
        Value: !Ref WebsiteUrl

    WebsiteThemeUrl: 
        Condition: installTheme
        Description: Installed website theme url
        Value: !Ref WebsiteThemeUrl

    WebsiteThemeValues: 
        Condition: installTheme
        Description: Installed website theme values
        Value: !Ref WebsiteThemeValues
